In [ ]:
l=[5,6,7,8]

list1=[i for i in l if i%2==0]
print(list1)

[6, 8]


In [ ]:
l=[5,6,7,8]

list1=[]

for i in l:
    if i%2==0:
        list1.append(i)
        
print(list1)

[6, 8]


In [ ]:
def squared(x):
    return x*x

num=[1,2,4,5]

num_squared= map(squared,num)

for i in num_squared:
    print(i)


1
4
16
25


In [ ]:
list2=[i*i for i in num]
print(list2)

list2[0]

[1, 4, 16, 25]


1

In [ ]:
my_tup = (5,12,10,18,43, 9, 11,6)

new_tup = tuple(filter(lambda x: (x%3) , my_tup))

print(new_tup)


(5, 10, 43, 11)


In [ ]:
import pandas as pd

Emp = {'Name': ['Ammy', 'Angela', 'Samuel', 'Danny'],
      'Age': [35,36,30,32],
      'City': ['New York', 'Chicago','Boston', 'Seattle']}



In [ ]:
print(Emp)

dir(Emp)


{'Name': ['Ammy', 'Angela', 'Samuel', 'Danny'], 'Age': [35, 36, 30, 32], 'City': ['New York', 'Chicago', 'Boston', 'Seattle']}


['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [ ]:
df = pd.DataFrame(Emp)

In [ ]:
df

Name  Age      City
0    Ammy   35  New York
1  Angela   36   Chicago
2  Samuel   30    Boston
3   Danny   32   Seattle

In [ ]:
df.loc[0:3,['Name', 'Age']]

Name  Age
0    Ammy   35
1  Angela   36
2  Samuel   30
3   Danny   32

In [ ]:
df['Name'][1]

'Angela'

In [ ]:
df.iloc[0:3,0:2]

Name  Age
0    Ammy   35
1  Angela   36
2  Samuel   30

In [ ]:
df.loc[df['Age']>30,['Name', 'Age']]

Name  Age      City
0    Ammy   35  New York
1  Angela   36   Chicago
3   Danny   32   Seattle

In [ ]:
df.iloc[(df['Age']>30).values,0:2]

Name  Age
0    Ammy   35
1  Angela   36
3   Danny   32

In [ ]:
(df['Age']>30).values

array([ True,  True, False,  True])

In [ ]:
df

Name  Age      City
0    Ammy   35  New York
1  Angela   36   Chicago
2  Samuel   30    Boston
3   Danny   32   Seattle

In [ ]:
f = lambda x: "Low mlg" if x<35 else "High mlg"
df['mlg'] = df.Age.apply(f)
print(df)

     Name  Age      City       mlg
0    Ammy   35  New York  High mlg
1  Angela   36   Chicago  High mlg
2  Samuel   30    Boston   Low mlg
3   Danny   32   Seattle   Low mlg


In [ ]:
df.Age[0]

35

In [ ]:
df['Age'].apply(f)[1]

'High mlg'

In [ ]:
import numpy as np

matrix = np.array([[1,2,3,1],[4,3,5,3],[4,7,6,5],[3,5,7,9]])

np.shape(matrix)

(4, 4)

In [ ]:
print(matrix)

[[1 2 3 1]
 [4 3 5 3]
 [4 7 6 5]
 [3 5 7 9]]


In [ ]:
print(matrix.diagonal())

[1 3 6 9]


In [ ]:
print(matrix.diagonal().sum())

19


In [ ]:
m = np.arange(1,10).reshape(3,3)

m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df.Age.max()

36

In [ ]:
car =  pd.DataFrame({'Brand': ['Ford', 'Tata', 'Tata', 'Maruti'],
      'Years': [2013,2024,2012,2001],
      'kms': [23000,4000,5000,32000],
      'City': ['New York', 'Boston','Boston', 'Seattle'],
      'Age': [35,36,30,32]})

In [ ]:
print(car.groupby('City').agg({'Age': ['mean','max'],'Years': ['mean','max']}))

           Age       Years      
          mean max    mean   max
City                            
Boston    33.0  36  2018.0  2024
New York  35.0  35  2013.0  2013
Seattle   32.0  32  2001.0  2001


In [ ]:
import pandas as pd

# Exemple de DataFrame
data = {'FirstName': ['John', 'Jane', 'John', 'Jane'],
        'LastName': ['Doe', 'Doe', 'Smith', 'Smith'],
        'Time': [10, 15, 20, 25]}

df = pd.DataFrame(data)

# Fonction pour agréger le temps par nom
def aggregate_time(dataframe):
    aggregated_data = dataframe.groupby(['FirstName', 'LastName']).agg({'Time': 'sum'}).reset_index()
    return aggregated_data

# Utilisation de la fonction
result = aggregate_time(df)

# Affichage du résultat
print(result)


  FirstName LastName  Time
0      Jane      Doe    15
1      Jane    Smith    25
2      John      Doe    10
3      John    Smith    20


In [ ]:
list(x=1:5, y= c())